
- name: Spin up a local development environment
  hosts: localhost
  gather_facts: True

  tasks:
  - name: Run Docker Compose
    command: docker-compose up -d
  
  - name: ping the database
    wait_for:
      host: localhost
      port: 5432
      delay: 0
      timeout: 1
      state: started

  - name: Run database migrations
    command: npx prisma migrate deploy


